### ISSUE TITLE
Feature request: Option to disable the completion popup

### ISSUE THREAD

**Issue by HebaruSan** [atom/ide-csharp#16]
Is there an option to turn off the completion popup?

Choices that actually resemble the current word are nowhere near the selection, and it pops up when I don't want to insert a word (such as typing curly braces at the end of a line); the net effect is that it disruptively pastes in words I don't want when I'm trying to type, but never actually helps me input words I do want. I tried disabling Code Actions, Code Formatting, Code Highlighting, and Datatips in the atom-ide-ui package, but it's still misinterpreting my keystrokes of {,enter as a desire to insert AccessViolationException:

![image](https://user-images.githubusercontent.com/1559108/32687174-6cc16680-c67c-11e7-9e8e-a497d4d052b1.png)

I like having the Diagnostics pane available so I'd prefer not to disable this package entirely again.

**Comment by damieng** [comment]
There is no way to switch off the diagnostics on their own unless you want to edit the package.json in your ide-csharp folder (remove the autocomplete block)

The suggestions will be improving soon so hopefully people won't need to switch them off.
