### ISSUE TITLE
Nuget Package Dependencies?

### ISSUE THREAD

**Issue by gabeio** [atom/ide-csharp#5]
This might be out of the scope of this project but I was wondering if Nuget packages currently (maybe I'm doing something wrong) or in the future are going to be supported.

Currently I do see the suggestions, and I have already installed Nuget packages which are my current project dependencies but the suggestion for using them in atom is "The type or namespace name 'Example' could not be found (are you missing a using directive or an assembly reference?)". But in visual studio it doesn't say anything is wrong and the project builds correctly.

Env:
Windows 7 x64
Atom 1.21.0-beta1 x64
atom-ide-ui 0.3.3
ide-csharp 0.6.0

**Comment by damieng** [comment]
That's really a question for the upstream language server this package depends on I think.

Their repo is at https://github.com/OmniSharp/omnisharp-node-client
