### ISSUE TITLE
No intellisense/autocomplete or other functionality

### ISSUE THREAD

**Issue by Xapphire13** [atom/ide-csharp#9]
I see this on all C# projects I have tried. But here is a simple repo

![image](https://user-images.githubusercontent.com/3392349/31741547-7ead43d0-b409-11e7-9aff-928d6e1338e3.png)

As you can see, I get a blank hover over showing only a pin icon. I would expect to see that `test` in this case is of type `string`; and `Console.Write`**`Line`**`()` should be an error.

The only errors I have in the console are:
![image](https://user-images.githubusercontent.com/3392349/31741587-a1a99dac-b409-11e7-99d1-f4ec08f8bbf8.png)

**Comment by damieng** [comment]
Can you type the following in the dev tools window console and restart then try again?  It will shed more light on what's going on;

`atom.config.set('core.debugLSP', true)`

**Comment by Xapphire13** [comment]
Here is the log file. Let me know if you need me to dig into any of the objects.

[atom log.txt](https://github.com/atom/ide-csharp/files/1396553/atom.log.txt)

**Comment by Xapphire13** [comment]
With the new update it started working (only when I have a `.csproj` though). Lots of functionality missing, but now I can start digging around =].
